### PR TITLE
Fix s3 reader

### LINKED ISSUE #232: If path is supposed to be a path it should automatically add trailing / if missing
If the `path` parameter is supposed to be a full path then it should automatically add a trailing `/` if it's missing. Otherwise you end up with the path munged with the file name which I don't think is intentional behavior.

### PR DESCRIPTION
**Pull request by macgyver603**
Fixes:
- s3 reader works again
- A trailing `/` is added to `path` if not included (fixes #232)

### CODE REVIEW

File: asset/_lib/fileName.js [hunk 1]
```diff
@@ -40,7 +46,11 @@ function parsePath(path) {
         splitPath.shift();
         splitPath.shift();
         if (splitPath.length > 0) {
-            pathInfo.prefix = splitPath.join('/');
+            // Protects from adding a leading '/' to the object prefix
+            if (splitPath[0].length !== 0) {
+                // Ensure the prefix ends with a trailing '/'
+                pathInfo.prefix = path.join(splitPath.join('/'), '/');
```
Comment (peterdemartini) [inline asset/_lib/fileName.js]:
```suggestion
                pathInfo.prefix = path.join(...splitPath, '/');
```

File: asset/_lib/fileName.js [hunk 2]
```diff
@@ -19,19 +21,23 @@ function getName(id, count, opConfig, pathOverride) {
...
+    const splitPath = objPath.split('/');
+    if (objPath[0] !== '/') {
         [pathInfo.bucket] = splitPath;
         splitPath.shift();
         if (splitPath.length > 0) {
-            pathInfo.prefix = splitPath.join('/');
+            // Protects from adding a leading '/' to the object prefix
+            if (splitPath[0].length !== 0) {
+                // Ensure the prefix ends with a trailing '/'
+                pathInfo.prefix = path.join(splitPath.join('/'), '/');
```
Comment (peterdemartini) [inline asset/_lib/fileName.js]:
```suggestion
                pathInfo.prefix = path.join(...splitPath, '/');
```
