### PR TITLE
fixed timeseries router and changed asset name

### LINKED ISSUE #234: timeseries router doesn't work
Looking at the code this is obviously broken. 

```
 TypeError: Cannot read property 'timeseries' of undefined
        at TimeseriesRouter.addPath (/Users/kstaken/projects/opensource/teraslice/assets/fb39272945ab4ec167866ae81a4323fe91071931/file_timeseries_router/processor.js:18:38)
        at Promise.all.slice.map (/Users/kstaken/projects/opensource/teraslice/assets/fb39272945ab4ec167866ae81a4323fe91071931/file_timeseries_router/processor.js:35:55)
        at Array.map (<anonymous>)
        at TimeseriesRouter.onBatch (/Users/kstaken/projects/opensource/teraslice/assets/fb39272945ab4ec167866ae81a4323fe91071931/file_timeseries_router/processor.js:35:34)

```

### LINKED ISSUE #235: Change the asset name to `file`
The asset name is set to `file-assets`, our other public assets do not include the `assets` in the name so in this case the name in asset.json should just be `file`

### PR DESCRIPTION
**Pull request by macgyver603**
- Renamed the `file_timeseries_router` to `timeseries_path_partitioner`
- Fixed that processor (fixes #234)
- Changed the path routing override attribute from `routingPath` to `file:partition` to match the convention `asset_name:attribute`  
- Renamed the asset bundle `file` to match the naming convention of other asset bundles (fixes #235)

### CODE REVIEW

File: test/timeseries_path_partitioner/processor-spec.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
+'use strict';
+
+const { TestContext } = require('@terascope/job-components');
+const { DataEntity } = require('@terascope/utils');
+const Processor = require('../../asset/timeseries_path_partitioner/processor');
+
+describe('Timeseries router', () => {
```
Comment (peterdemartini) [inline test/timeseries_path_partitioner/processor-spec.js]: Since this is a new spec file, this should use the `WorkerHarness` from `teraslice-test-harness`.

Comment (macgyver603) [reply test/timeseries_path_partitioner/processor-spec.js]: Updated test to use teraslice-test-harness

File: test/timeseries_path_partitioner/processor-spec.js [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+    const data = [
+        DataEntity.make(
+            {
+                date: '2020-01-17T19:21:52.159Z',
+                text: 'test data'
+            }
+        )
+    ];
+
+    beforeAll(async () => {
```
Comment (peterdemartini) [inline test/timeseries_path_partitioner/processor-spec.js]: This beforeAll isn’t needed because it only applies to one test and this worker harness instance should be created in your `it` block (like the other ones)

File: test/timeseries_path_partitioner/processor-spec.js [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+            _op: 'timeseries_path_partitioner',
+            base_path: '/data',
+            date_field: 'date',
+            prefix: '',
+            type: 'daily'
+        }, {});
+        await harness.initialize();
+    });
+
+    afterAll(async () => {
```
Comment (peterdemartini) [inline test/timeseries_path_partitioner/processor-spec.js]: This afterAll should be a afterEach since it should cleanup after each new instance of the harness (which are created in your it blocks)

File: test/timeseries_path_partitioner/processor-spec.js (hunk 2 above)
Comment (macgyver603) [reply test/timeseries_path_partitioner/processor-spec.js]: Fixed

File: test/timeseries_path_partitioner/processor-spec.js (hunk 3 above)
Comment (macgyver603) [reply test/timeseries_path_partitioner/processor-spec.js]: Fixed
